# docker-compose.yml
version: "3.8"
services:
  app:
    restart: always
    build: .
    depends_on:
      - db
    environment:
#      NODE_ENV: development
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: pgtest
      DB_PASSWORD: pgtest123
      DB_NAME: pgtest
      PORT: 5000
    links:
      - db
    ports:
      - "5000:5000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgtest
      POSTGRES_PASSWORD: pgtest123
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
